name: Release
on:
  push:
    branches:
    - main
jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Run gofmt
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
    - name: Run vet
      run:  go vet ./...
    - name: Bump version and tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
